[package]
name = "tinyrick_macros"
description = "procedural macros for scheduling development tasks"
version = "0.0.5"
edition = "2024"
authors = ["Andrew Pennebaker <n4jm4@pm.me>"]
license = "0BSD"
repository = "https://github.com/mcandre/tinyrick_macros"
documentation = "https://docs.rs/tinyrick_macros/"
exclude = [
    "*.mk",
    ".editorconfig",
    ".github",
    ".rubberstamp",
    ".tool-versions",
    "makefile",
]

[dependencies]
ctor = "1.0.13"
proc-macro2 = "1.0.107"
quote = "1.0.42"
syn = { version = "3.0.3", features = ["full"] }
tinyrick_models = "0.0.3"

[lib]
name = "tinyrick_macros"
proc-macro = true
